<script setup>
import { ref, onMounted, watch } from 'vue';
import { useRoute } from 'vue-router';
import { queryVariables } from '../utils/searchUtils';

const route = useRoute();
const id = ref(route.params.id);

const title = ref("");
const year = ref("");
const demographic = ref("");
const min_age = ref(0);
const max_age = ref(100);
const description = ref("");
const variables = ref([]);
const document_name = ref("")

const parseDescription = (text) => {
  return text[0] === '"' ? text.slice(1, -1) : text;
}

const fetchData = async () => {
  console.log(`ID being queried: ${id.value}`);
  const result = await queryVariables(parseInt(id.value, 10));
  console.log(result)
  if (result && result.length > 0) {
    title.value = result[0][2];
    year.value = result[0][3];
    demographic.value = result[0][4];
    min_age.value = result[0][5];
    max_age.value = result[0][6];
    description.value = parseDescription(result[0][8]);
    document_name.value = result[0][9]
    variables.value = result.map((variable) => {
      return {name: variable[0], description: variable[1]}
    })
  }
}

onMounted(fetchData);
watch(() => route.params.id, (newId) => {
  id.value = newId;
  fetchData();
})

const viewData = () => {
  const downloadLink = `${import.meta.env.BASE_URL}linmacse/${document_name.value}`;
  window.open(downloadLink, '_blank');
};



const requestDataLink = 'https://docs.google.com/forms/d/e/1FAIpQLSc5SQeDOZv6hBp5gyCF5byiOri6_zCcU5gSk5Wj0PucAB52Dw/viewform'; 
</script>

<template>
  <div class="container">
    <div class="title-container">
      <h1>{{ title }}</h1>
      <a :href="requestDataLink" target="_blank" rel="noopener noreferrer">
        <Button label="Request Data" icon="pi pi-envelope" size="small" iconPos="right" rounded style="color: var(--text-color);"/>
      </a>
    </div>
    <div class="metadata-container">
      <h3><u>Project</u>: {{ year }}</h3>
      <h3><u>Demographic</u>: {{ demographic == "MOM" ? "Mothers" : "Children" }}</h3>
      <h3><u>Ages</u>: {{ min_age }} to {{ max_age }}</h3>
    </div>
    <div class="desc-container">
      <div class="inner-desc-container">
        <h2>Description</h2>
        <div class="generated-info" v-tooltip.top="'Description auto-generated with ChatGPT. Use with caution.'">
          <i class="pi pi-bolt" style="font-size: 14px"></i>
          <div>Auto-Generated by GenAI</div>
        </div>
      </div>
      {{ description }}
    </div>
    <div class="variables-container">
      <div class="variables-subtitle-container">
        <h2>Variables</h2>
        <Button label="View Metadata" @click="viewData" rounded style="color: var(--text-color);"/>
      </div>
      <DataTable 
        :value="variables" 
        stripedRows 
        showGridlines 
        paginator 
        :rows="7" 
        :rowsPerPageOptions="[5, 7, 10, 15, 20]"
        tableStyle="min-width: 50rem"
      >
        <Column field="name" header="Name" style="width: 20%"></Column>
        <Column field="description" header="Description" style="width: 80%"></Column>
      </DataTable>
    </div>
  </div>
</template>

<style scoped>
.container {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.title-container {
  display: flex;
  justify-content: start;
  align-items: center;
  gap: 1rem;
}

.metadata-container {
  display: flex;
  justify-content: start;
  align-items: center;
  gap: 2rem;
}

.desc-container {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.inner-desc-container {
  display: flex;
  flex-direction: row;
  gap: 1rem;
}

.generated-info {
  display: flex;
  gap: 4px;
  justify-content: center;
  align-items: center;
  border: 1px solid gray;
  background-color: #FAFAFA;
  border-radius: 0.5rem;
  padding: 0 8px;
  font-size: 12px;
  background-color: var(--michigan-maize);
}

.variables-container {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.variables-subtitle-container {
  display: flex;
  justify-content: space-between;
}

:deep(.p-datatable) {
  width: 100%;
  border: 1px solid black;
}
</style>
